# Generated by Django 4.2.5 on 2023-09-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0003_alter_booth_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="booth",
            name="locate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="booth",
            name="content",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
