# Generated by Django 4.2.5 on 2023-09-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0004_booth_locate_alter_booth_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
