# Generated by Django 4.2.5 on 2023-09-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='name',
            new_name='nickname',
        ),
    ]
