# Generated by Django 4.2.5 on 2023-09-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitor", "0002_rename_name_visitor_nickname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visitor",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="visitor",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
